#
installationId: changeme
#
homeUrl: http://digiburo.com/hal/mellow-elephant1.json
#homeUrl: http://digiburo.com/hal/mellow-elephant-test1.json
#
# legal receiver types: bc780
receiverType: bc780
#
receiverProxy: /home/gsc/git/mellow-elephant-py/bin/sampler1a
#
#dataDirectory: /Users/gsc/elephant
dataDirectory: /home/gsc/elephant
#
runMode: once
#runMode: always
#
frequencyBands:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
#
