#
installationId: 820d1021-75d6-4c83-8487-edbe4b433858
#
# legal receiver types: bc780
receiverType: bc780
#
dbDirectory: /Users/gsc/IdeaProjects/mellow-elephant/db
grafDirectory: /Users/gsc/IdeaProjects/mellow-elephant/graphs
pickleDirectory: /Users/gsc/IdeaProjects/mellow-elephant/observations
#
pidLockFile: /tmp/lock.pid
#
#serialDevice: /dev/ttyUSB0
serialDevice: /dev/ttyStub
#
runMode: once
#runMode: always
runDirection: low2high
#
frequencyBands:
    - 10
    - 11
    - 14
#
