#
installationId: 820d1021-75d6-4c83-8487-edbe4b433858
#
# legal receiver types: bc780, rtlsdr, stub
#receiverType: bc780
#receiverType: rtlsdr
receiverType: bc780
#
pickleDirectory: /tmp
#
pidLockFile: /tmp/lock.pid
#
serialDevice: bogus
#
runMode: once
#runMode: always
runDirection: low2high
#
frequencyBands:
    - 13
    - 14
#