#
installationId: 67ec00b2-2c50-49f6-834f-c565fd8f98dd
#
# legal receiver types: bc780, stub
#receiverType: bc780
receiverType: stub
#
receiverProxy: /home/gsc/git/mellow-elephant-c/linux/sampler1/sampler_usb0
#
pickleDirectory: /tmp
#
pidLockFile: /tmp/lock.pid
#
serialDevice: bogus
#
runMode: once
#runMode: always
runDirection: low2high
#
frequencyBands:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
#
